content_item:
  - uniquely_named
  - listable
  - publishable
  - translatable
  - blueprintable
  - metadata

block: &content_item
component: &content_item

image:
  - uniquely_named
  - uploadable

:document, :uniquely_named, :translatable, :validatable,
                 :blueprintable, :publishable,
                 :taggable, :renderable,
                 :listable #, :extendable
                 # :images

